apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory      /* the address of the issuer with which cert manager will talk */
    email: 'ste.grider@gmail.com'                               /* give a real email address for some notification, whatever */
    privateKeySecretRef:
      name: letsencrypt-prod                                    /* This value letsencrypt sends to us, we just provide here */
    http01: {}                                                  /* we want to use the http version of getting the certificate */
